### ISSUE TITLE
Fails to compile 68000 emulation

### ISSUE THREAD

**Issue by jbquirk** [EtchedPixels/RC2014#18]
When compiling the module m68kdasm.c gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0 complains of a array being to small around 334 I increased the size of the static char array and this fixed it.  
form this static char str[15]; to static char str[32]; this was just a hack to get it to compile I'm not using the 68K emulation so i'm not sure if this breaks it.
I have not had a deep look at the code to understand the issue.

**Comment by mrdudz** [comment]
there is a fix in pr #23 and pr #24

@EtchedPixels please merge? Its a trivial fix afterall :)

**Comment by EtchedPixels** [comment]
Done - using snprintf to stop gcc trying to be overclever and also make the size explicit
