### ISSUE TITLE
How to exit the RC2014 emulator?

### ISSUE THREAD

**Issue by scherrey** [EtchedPixels/RC2014#30]
Running Linux squire 5.14.0-4mx-amd64 #1 SMP Debian 5.14.16-1~mx21+1 (2021-11-05) x86_64 GNU/Linux

I booted into forth but can't figure out any way to exit the emulator or reboot it. Doesn't matter which boot option I use (although I'm partial to FORTH). I'm guessing rebooting isn't really a think for RC2014s.

Also - I see the emulator reports a few drives. As I recall Z80 normally talks to devices via ports rather than memory maps. Are there any docs on how to address these drives? I see CamelForth apparently doesn't come with block support. I'm curious to see if I can't add it. Would appreciate any docs on low level system access to the RC2014 with RomWBW. Are CP/M calls available while in the ROM Forth? I've got my RC2014 kit that I'm prepping to build so would love to get comfy on the emulator until that's going.

Thanks and if there's a better place for me to ask such questions please let me know.

`
scherrey@squire:~/projects/RC2014/RC2014
$ ./rc2014 -s -r ../RCZ80_std.rom -b

RomWBW HBIOS v3.0.1, 2020-04-04

RC2014 Z80 @ 7.372MHz
0 MEM W/S, 1 I/O W/S, INT MODE 1
512KB ROM, 512KB RAM

SIO0: IO=0x80 SIO MODE=115200,8,N,1
SIO1: IO=0x82 SIO MODE=115200,8,N,1
DSRTC: MODE=STD IO=0xC0 NOT PRESENT
MD: UNITS=2 ROMDISK=384KB RAMDISK=384KB
IDE: IO=0x10 MODE=RC
IDE0: NO MEDIA
IDE1: NO MEDIA
PPIDE: IO=0x20 PPI NOT PRESENT

Unit        Device      Type              Capacity/Mode
----------  ----------  ----------------  --------------------
Char 0      SIO0:       RS-232            115200,8,N,1
Char 1      SIO1:       RS-232            115200,8,N,1
Disk 0      MD1:        RAM Disk          384KB,LBA
Disk 1      MD0:        ROM Disk          384KB,LBA
Disk 2      IDE0:       Hard Disk         --
Disk 3      IDE1:       Hard Disk         --

RC2014 Boot Loader

ROM: (M)onitor (C)P/M (Z)-System (F)orth (B)ASIC (T)-BASIC (P)LAY (U)SER ROM  
Disk: (0)MD1 (1)MD0 (2)IDE0 (3)IDE1 

Boot Selection? F

Loading Camel Forth...

Z80 CamelForth v1.02  25 Jan 1995, ROMWBW 19 Oct 2019
1 2 + . 3 
ok dir dir?
words words?
WORDS COLD .S WORDS ENVIRONMENT? DEPTH MOVE WITHIN LEAVE +LOOP LOOP ENDLOOP DO L> >L REPEAT WHILE AGAIN UNTIL BEGIN ELSE THEN IF POSTPONE ['] ; : IMMEDIATE REVEAL HIDE ] [ RECURSE DOES> (DOES>) CREATE ( [CHAR] CHAR ' ABORT" ?ABORT ABORT QUIT EVALUATE INTERPRET ?NUMBER >NUMBER ?SIGN DIGIT? LITERAL FIND IMMED? NFA>CFA NFA>LFA WORD >COUNTED /STRING SOURCE C, , ALLOT HERE HEX DECIMAL . U. SIGN #> #S # >DIGIT <# HOLD UD* UD/MOD ." S" (S") TYPE ACCEPT UMAX UMIN SPACES SPACE CR COUNT 2OVER 2SWAP 2DUP 2DROP 2! 2@ MIN MAX */ */MOD MOD / /MOD * FM/MOD SM/REM M* DABS ?DNEGATE DNEGATE ABS ?NEGATE S>D #INIT UINIT R0 L0 PAD S0 LP HP LATEST 'SOURCE DP STATE BASE >IN U0 TIB TIBSIZE BL !DEST ,DEST ,BRANCH ,EXIT !COLON ,CF !CF COMPILE, >BODY CHARS CHAR+ CELLS CELL+ CELL ALIGNED ALIGN S= SCAN SKIP CMOVE> CMOVE FILL UM/MOD UM* UNLOOP J I (+loop) (loop) (do) ?branch branch U> U< > < <> = 0< 0= +! RSHIFT LSHIFT 2/ 2* >< 1- 1+ NEGATE INVERT XOR OR AND - M+ + PC@ PC! C@ @ C! ! RP! RP@ SP! SP@ R@ R> >R TUCK NIP ROT OVER SWAP DROP ?DUP DUP bye KEY KEY? SAVEKEY EMIT USER CONSTANT VARIABLE EXECUTE lit EXIT 
ok EXIT 
ok EXIT 
ok QUIT
`

**Comment by EtchedPixels** [comment]
ctrl-\ exits the emulator itself.

**Comment by scherrey** [comment]
Thanks all for the info. Can't believe I forgot "bye" for CamelForth - but it has been 30+ years. Is ctrl-\ documented anywhere?

FYI - The HBIOS docs in the RomWBW was really what I was looking to discover. Maybe I can add some storage device support in CamelForth ROM by calling the HBIOS.

**Comment by wwarthen** [comment]
> FYI - The HBIOS docs in the RomWBW was really what I was looking to discover. Maybe I can add some storage device support in CamelForth ROM by calling the HBIOS.

Possibly.  But keep in mind that HBIOS alone just provides disk sector I/O.  It does not implement a filesystem of any kind.

-Wayne

**Comment by guidol70** [comment]
> Thanks all for the info. Can't believe I forgot "bye" for CamelForth - but it has been 30+ years. Is ctrl-\ documented anywhere?

On my systems ctrl-\ does only work in graphical (X) Terminal.
On a text-console based Terminal (on windows - there like putty) I can hold the ALT-key press 2 and 8 for 28 on the Numpad and release the ALT-Key to generate the ASCII-Char 28 which is SIGQUIT.
Did work for me in the Z80-MBC2 and the RC2014-Emulation :)
