### ISSUE TITLE
Freezes with BASIC and CP/M Monitor

### ISSUE THREAD

**Issue by cpswan** [EtchedPixels/RC2014#6]
#### Issue description

Emulation freezes at:

```
Z80 SBC By Grant Searle

Memory top?
```

when started with `./rc2014 -a -e 0`

and 

```
Press [SPACE] to activate console
```

when started with `./rc2014 -a -e 4 -p`

The Small Computer Monitor seems to work fine with `./rc2014 -a -e 7`

#### Steps to reproduce the issue

Built `rc2014` with `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)` and running in an Ubuntu 18.04.2 VM with 1 CPU and 1GB RAM in VMware Workstation 12.5.2

rc2014.rom is [Factory ROM R0001009.BIN](https://github.com/RC2014Z80/RC2014/blob/master/ROMs/Factory/R0001009.BIN)

#### What's the expected result?

Pressing Enter should start BASIC, or space, x, y should launch CP/M

#### What's the actual result?

System freezes

#### Additional details

Example debug output (repeating section) from `./rc2014 -a -d 1 -e 4 -p` :

```
<snip>
W 40ac[23] = 9D
W 40ad[23] = 01
R 0124[22] = 3A
R 0125[22] = 89
R 0126[22] = 40
R 4089[23] = 00
R 0127[22] = FE
R 0128[22] = 00
R 0129[22] = C9
R 40ac[23] = 9D
R 40ad[23] = 01
R 019d[22] = 28
R 019e[22] = E7
R 0186[22] = CD
R 0187[22] = 1E
R 0188[22] = 01
W 40ac[23] = 89
W 40ad[23] = 01
R 011e[22] = 3A
R 011f[22] = 44
R 0120[22] = 40
R 4044[23] = 00
R 0121[22] = FE
R 0122[22] = 00
R 0123[22] = C9
R 40ac[23] = 89
R 40ad[23] = 01
R 0189[22] = 28
R 018a[22] = 0F
R 019a[22] = CD
R 019b[22] = 24
R 019c[22] = 01
W 40ac[23] = 9D
W 40ad[23] = 01
R 0124[22] = 3A
R 0125[22] = 89
R 0126[22] = 40
R 4089[23] = 00
R 0127[22] = FE
R 0128[22] = 00
R 0129[22] = C9
R 40ac[23] = 9D
R 40ad[23] = 01
R 019d[22] = 28
R 019e[22] = E7
R 0186[22] = CD
R 0187[22] = 1E
R 0188[22] = 01
W 40ac[23] = 89
W 40ad[23] = 01
R 011e[22] = 3A
R 011f[22] = 44
R 0120[22] = 40
R 4044[23] = 00
R 0121[22] = FE
R 0122[22] = 00
R 0123[22] = C9
R 40ac[23] = 89
R 40ad[23] = 01
R 0189[22] = 28
R 018a[22] = 0F
R 019a[22] = CD
R 019b[22] = 24
R 019c[22] = 01
W 40ac[23] = 9D
W 40ad[23] = 01
R 0124[22] = 3A
R 0125[22] = 89
R 0126[22] = 40
R 4089[23] = 00
R 0127[22] = FE
R 0128[22] = 00
R 0129[22] = C9
R 40ac[23] = 9D
R 40ad[23] = 01
R 019d[22] = 28
R 019e[22] = E7
R 0186[22] = CD
R 0187[22] = 1E
R 0188[22] = 01
W 40ac[23] = 89
W 40ad[23] = 01
R 011e[22] = 3A
R 011f[22] = 44
R 0120[22] = 40
R 4044[23] = 00
R 0121[22] = FE
R 0122[22] = 00
R 0123[22] = C9
R 40ac[23] = 89
R 40ad[23] = 01
R 0189[22] = 28
R 018a[22] = 0F
R 019a[22] = CD
R 019b[22] = 24
R 019c[22] = 01
W 40ac[23] = 9D
W 40ad[23] = 01
R 0124[22] = 3A
R 0125[22] = 89
R 0126[22] = 40
R 4089[23] = 00
R 0127[22] = FE
R 0128[22] = 00
R 0129[22] = C9
<snip>
```

Similar results when using `./rc2014 -s -r SIO32K.BIN` when the ROM is [SIO2/INTSIO.HEX](https://github.com/RC2014Z80/RC2014/blob/master/ROMs/SIO2/INTSIO.HEX) joined to [SIO2/BAS32K.HEX](https://github.com/RC2014Z80/RC2014/blob/master/ROMs/SIO2/BAS32K.HEX) and saved to a single .bin file, though in this case BASIC freezes at `Z80 SBC By Grant Searle` without even asking about Memory Top?

[Snake](https://github.com/RC2014Z80/RC2014/tree/master/ROMs/snake) kind of works (when put into an 8k rom file), though the snake only moves when a key is pressed rather than free running.

**Comment by EtchedPixels** [comment]
The ACIA code is a bit basic and minimal. That poked me into actually trying to fix it properly.

Still need to look why ROMWBW fails but this seems to fix the basic case.

Will look at the SIO2 case

Snake I think just keeps polling the uart data register and right now that fools the emulator

**Comment by cpswan** [comment]
Thanks Alan. That's done it - BASIC and CP/M now working as expected (and I can proceed with my CPMish experiments).
