### ISSUE TITLE
Cannot exit emulator in the Linux Bash Shell on Windows 10

### ISSUE THREAD

**Issue by linker3000** [EtchedPixels/RC2014#7]
I copied the working RC2014 emulator/CF image folder structure from my laptop running Linux Mint 19 to the Linux (Ubuntu) Bash shell under Windows 10 on another machine. 

The emulator seemed to work as expected (runs Wordstar and various commands I tried), but CTRL-\ does not exit the emulator (does nothing).

The emulator was first downloaded and setup in May this year and uses SCMonitor-v100-R3-RC2014-32k-ROM
 
Any thoughts, or anything I can do to help debug if needed?

**Comment by EtchedPixels** [comment]
WSL has a history of not handling things like that correctly. Not sure there is anything I can do about it.

Feel free to debug it but I think you'll find the process simply never receives SIGQUIT as it should

**Comment by guidol70** [comment]
got the same problem her ein puTTY on Windows not getting the AIGQUIT to the Z80-MBC2.
The screen only show the backslash.
After I did found out that Ctrl-\ is ASCII 28 I usd the old - hold ALT-key, Type 28 on the Num-block and release ALT-key - sequence from DOS-times and it did work.
Using this key-combination I can quit the emulator from inside of puTTY :)
